### ISSUE TITLE
[1.15.1] Meta Chest Crash in Mod List

### ISSUE THREAD

**Issue by realTIMematrix** [Nukeologist/MetaChests#2]
Hi,

if i click in the Mod List to see if Meta Chests has Options or not the game crashed. Only Meta Chests and Forge installed. No other interactions:

[https://pastebin.com/SGsydCN3](https://pastebin.com/SGsydCN3)

best regards

**Comment by bignelli** [comment]
Thanks for the report, will investigate soon

**Comment by bignelli** [comment]
Interesting, I can't reproduce this on the development environment, but I can in production. Seems like Forge is looking for a logo file where there isn't. Next build should fix.
