### ISSUE TITLE
1.15.2 crash when opening metachest

### ISSUE THREAD

**Issue by SDUBZ** [Nukeologist/MetaChests#3]
[crash-2020-03-07_21.09.55-client.txt](https://github.com/Nukeologist/MetaChests/files/4301675/crash-2020-03-07_21.09.55-client.txt)

forge: 1.15.2-31.1.18
metachest : MetaChests-1.15.1-1.4.1

**Comment by bignelli** [comment]
Looks like some Forge internals I relied on changed before the first RB. My fault for not looking, should be easy fix
